### ISSUE TITLE
Path problems when loading a native library from inside Python package

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#1112]
Your user guide clearly states that the goal of the library _does not_ extend to the packaging side of things, so I completely understand if you have no bandwidth to deal with these questions. Feel free to close the issue anytime. But I asked the question on Stack Overflow and just wanted to give it visibility here, in case the devs who work on the Python language bindings know the answer!

I basically cannot load the native lib from Python because it doesn't by default look "into itself" for native libraries, and so the only current way I know how to make it work is to go and fiddle with the auto-generated bindings, which I'd rather not touch if I can fix my problem another way!

[Stack Overflow question](https://stackoverflow.com/questions/70088764/path-problems-when-loading-a-native-library-from-inside-python-package).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-115)
┆friendlyId: UNIFFI-115

**Comment by mhammond** [comment]
This sounds like #1075?

**Comment by thunderbiscuit** [comment]
Ah yes maybe! I had in mind that the fix was probably on the Python packaging side of things, but indeed I have found that I can fix by simply changing where the module looks for the native lib. I just wasn't sure if this was the "right" way to do it.

I'm not 100% sure on what the bindings code coming from #1075 will be just by looking at the thread however. Let me pull in the PR and see if it works on my side, in which case that will be the fix for me!

**Comment by thunderbiscuit** [comment]
Trying to build the Python bindings with the crate version set to the PR in 1075, but I'm getting the error of `Please check that you depend on version 0.14.1 of the `uniffi` crate.`, as per the user guide. Sorry I'm a bit new to Rust... How would you go about testing with the branch in the PR?

My `Cargo.toml`:
```toml
[dependencies]
bdk = { version = "0.13", features = ["all-keys", "use-esplora-ureq"] }
uniffi_macros = "0.14.1"
# uniffi = "0.14.1"
uniffi = { git = "https://github.com/badboy/uniffi-rs", branch = "py:load-with-path" }
thiserror = "1.0"

[build-dependencies]
uniffi_build = "0.14.1"
```
