### ISSUE TITLE
Split cli out of uniffi_bindgen

### ISSUE THREAD

**Issue by messense** [mozilla/uniffi-rs#1416]
`uniffi_bindgen` as a library is quite bloated at the moment, for example

```toml
[build-dependencies]
uniffi_build = {version = "0.8", features = [ "builtin-bindgen" ]}
```

`builtin-bindgen` would depends on `clap`. 

I wonder if it's acceptable to split the cli out to a separate crate say `uniffi_bindgen_cli` like [what bindgen does](https://github.com/rust-lang/rust-bindgen/tree/master/bindgen-cli)? 

I'm using `uniffi_bindgen::generate_bindings` function in [maturin](https://github.com/PyO3/maturin/blob/4bceaa57039e00f3063c918a578730dd09e4308e/src/module_writer.rs#L878) and would like to avoid pulling in clap 3.x.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-215)
┆Issue Number: UNIFFI-215
