### ISSUE TITLE
run_uniffi_bindgen() not found in uniffi

### ISSUE THREAD

**Issue by julian-baumann** [mozilla/uniffi-rs#1452]
The documentation seems to be outdated. Certain functions and macros do not exist as described.
Like `uniffi::generate_scaffolding("./src/math.udl").unwrap()` found [here](https://mozilla.github.io/uniffi-rs/tutorial/Rust_scaffolding.html), what should probably be `uniffi_build::generate_scaffolding("./src/math.udl").unwrap()` as it is in the application-services repository. 

But I still can't figure out how to build the foreign language bindings.
`run_uniffi_bindgen()` doesn't seem to exist, as this error message hints
```
2 | uniffi::run_uniffi_bindgen().unwrap()
  | ^^^^^^^^^^^^^^^^^^ not found in `uniffi
```

My Cargo.toml:
```toml
[package]
name = "data_rct_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "data_rct"

[[bin]]
name = "run-uniffi-bindgen"
path = "run-uniffi-bindgen.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_rct = { package = "data_rct", path = "../../../data_rct" }
uniffi = "0.22.0"
uniffi_macros = "0.22.0"

[build-dependencies]
uniffi = "0.22.0"
uniffi_build = { version = "0.22.0", features=["builtin-bindgen"] }
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-229)
┆Issue Number: UNIFFI-229
