### ISSUE TITLE
Undefined symbols

### ISSUE THREAD

**Issue by teovillanueva** [mozilla/uniffi-rs#1461]
Hello!

For some reason when I build the library and try to use it in my iOS project i get this error.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/41754896/214930865-d4e79361-b850-48e5-a75e-8a92db970886.png">

I looked at the static lib symbols but couldn't find them with `nm libmylib_unifii.a`

This is how im building the library
```sh
cargo build --target x86_64-apple-ios
cargo build --target aarch64-apple-ios-sim

lipo -create target/aarch64-apple-ios-sim/debug/libmylib_unifii.a target/x86_64-apple-ios/debug/libmylib_unifii.a -output target/libmylib_unifii.a

uniffi-bindgen generate ./src/mylib.udl -l swift --out-dir ./generated/ios

cp target/libmylib_unifii.a ../ios/mylib/libmylib_unifii.a
cp generated/ios/* ../ios/mylib
```

I also tried using the library with `swiftc` building it for `aarch64-apple-darwin` and still I have the same issue of the symbols being undefined.

This is my `Cargo.toml`
```toml
[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "mylib_unifii"

[dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", branch = "main" }

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", branch = "main", features = ["build"] }

[dev-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", branch = "main", features = ["bindgen-tests"] }

```

`uniffi.toml`
```
[bindings.kotlin]
package_name = "me.teovillanueva.mylib_unifii"
cdylib_name = "mylib_unifii"

[bindings.python]
cdylib_name = "mylib_unifii"

[bindings.ruby]
cdylib_name = "mylib_unifii"

[bindings.swift]
cdylib_name = "mylib_unifii"
```

`build.rs`
```rust
fn main() {
    uniffi::generate_scaffolding("./src/mylib.udl").unwrap();
}
```

`lib.rs`
```rust
fn add(a: u32, b: u32) -> u32 {
    a + b
}

uniffi::include_scaffolding!("mylib");
```

`mylib.udl`
```
namespace mylib {
  u32 add(u32 a, u32 b);
};
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/UNIFFI-233)
┆Issue Number: UNIFFI-233
