### ISSUE TITLE
Add documentation examples of potential optimizations for released libraries

### ISSUE THREAD

**Issue by thunderbiscuit** [mozilla/uniffi-rs#1630]
Hi there! Our team uses a custom release profile to reduce the size of the binaries and final libraries. I'm wondering if the Mozilla team has any special insights into what works best for minimizing the size of the libraries, and think there might be value in adding such examples and discussion of tradeoffs in the user guide.

This is our current release profile. Would love to hear what other folks use and potential improvements/tradeoffs!
```toml
[profile.release-smaller]
inherits = "release"
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
```
