### ISSUE TITLE
Cannot run on on x86_64: dlopen failed: cannot locate symbol "__extenddftf2"

### ISSUE THREAD

**Issue by mike-lloyd03** [mozilla/uniffi-rs#1923]
Since adding sqlx and Sqlite to my Rust library, I cannot run on x86_64 architecture (using the emulator). Running on an arm devices works fine.

After compiling, when trying to open the app, I get the following error:

```
FATAL EXCEPTION: main
    Process: com.example.calc2, PID: 6540
    java.lang.UnsatisfiedLinkError: Unable to load library 'calc2':
    dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~0dYdDhJk-dWOTncQbfI5CA==/com.example.calc2-XqOwTb5ci0LpjoMI8NBwug==/base.apk!/lib/x86_64/libcalc2.so"...
    dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~0dYdDhJk-dWOTncQbfI5CA==/com.example.calc2-XqOwTb5ci0LpjoMI8NBwug==/base.apk!/lib/x86_64/libcalc2.so"...
    dlopen failed: cannot locate symbol "__extenddftf2" referenced by "/data/app/~~0dYdDhJk-dWOTncQbfI5CA==/com.example.calc2-XqOwTb5ci0LpjoMI8NBwug==/base.apk!/lib/x86_64/libcalc2.so"...
    Native library (android-x86-64/libcalc2.so) not found in resource path (.)
```

I did some Googling around and it seems like `__extenddftf2` is a C library used by Sqlite for handling floating point values.

It's possible this error has nothing to do with uniffi and I may be using the wrong NDK version but I thought I'd ask here first.

Full project is here: https://github.com/mike-lloyd03/SymCalc2

<details>
<summary>Cargo.toml</summary>

```toml
[package]
name = "calc2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "calc2"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi_bindgen.rs"

[dependencies]
async-std = "1.12.0"
kalk = { version = "3.0.4", default-features = false }
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-async-std"] }
thiserror = "1.0.51"
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", branch = "main", features = [
  "cli",
] }

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs.git", branch = "main", features = [
  "build",
] }
```

</details>

<details>
<summary>build.gradle</summary>

```gradle
plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.mozilla.rust-android-gradle.rust-android'
}

android {
    namespace 'com.example.calc2.shared'
    compileSdk 34

    ndkVersion "26.1.10909125"

    defaultConfig {
        minSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    sourceSets {
        main.java.srcDirs += "${projectDir}/../../generated"
    }
}

dependencies {
    implementation "net.java.dev.jna:jna:5.13.0@aar"

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

apply plugin: 'org.mozilla.rust-android-gradle.rust-android'

cargo {
    module  = "../.."
    libname = "calc2"
    targets = ["arm", "arm64", "x86", "x86_64"]
}

afterEvaluate {
    // The `cargoBuild` task isn't available until after evaluation.
    android.libraryVariants.configureEach { variant ->
        def productFlavor = ""
        variant.productFlavors.each {
            productFlavor += "${it.name.capitalize()}"
        }
        def buildType = "${variant.buildType.name.capitalize()}"

        tasks.named("compileDebugKotlin") {
            it.dependsOn(tasks.named("typesGen"), tasks.named("bindGen"))
        }

        tasks.named("generate${productFlavor}${buildType}Assets") {
            it.dependsOn(tasks.named("cargoBuild"))
        }
    }
}


tasks.register('bindGen', Exec) {
    def outDir = "${projectDir}/../../generated"
    workingDir "../../"
    commandLine("sh", "-c",
            """\
            cargo build --release && \
            target/release/uniffi-bindgen generate \
            --library target/release/libcalc2.so \
            --language kotlin \
            --out-dir $outDir
            """)
}

tasks.register('typesGen', Exec) {
    workingDir "../../"
    commandLine("sh", "-c", "cargo build")
}

tasks.whenTaskAdded { task ->
    if ((task.name == 'javaPreCompileDebug' || task.name == 'javaPreCompileRelease')) {
        task.dependsOn 'cargoBuild'
    }
}

tasks.whenTaskAdded { task ->
    if ((task.name == 'mergeDebugJniLibFolders' || task.name == 'mergeReleaseJniLibFolders')) {
        task.dependsOn 'cargoBuild'
    }
}
```

</details>
