### ISSUE TITLE
`uniffi::custom_type!` should have `try_lower` instead of just `lower`

### ISSUE THREAD

**Issue by kriswuollett** [mozilla/uniffi-rs#2425]
A possible common use case could be serializing a complex value instead of using Uniffi for everything like a structured record like a JSON type. For example I'd expect to be able to have a failure when lowering:

```rust
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[cfg_attr(feature = "uniffi", derive(uniffi::Record))]
pub struct Metadata(serde_json::Value);

uniffi::custom_type!(Metadata, String, {
    try_lower: |s| serde_json::to_string(&s).context("Metadata serialization failed"),
    try_lift: |s| serde_json::from_str(&s).context("Metadata deserialization failed"),
});

```

I assumed that was possible, but found out only `lower` that doesn't return an error is available. A generic structure like a [`serde_json::Value` may be invalid if non-string keys are used](https://github.com/serde-rs/json/blob/1174c5f57db44c26460951b525c6ede50984b655/src/ser.rs#L2202C1-L2219C2):

```rust
/// Serialize the given data structure as a String of JSON.
///
/// # Errors
///
/// Serialization can fail if `T`'s implementation of `Serialize` decides to
/// fail, or if `T` contains a map with non-string keys.
#[inline]
pub fn to_string<T>(value: &T) -> Result<String>
where
    T: ?Sized + Serialize,
{
    let vec = tri!(to_vec(value));
    let string = unsafe {
        // We do not emit invalid UTF-8.
        String::from_utf8_unchecked(vec)
    };
    Ok(string)
}
```

**Comment by kriswuollett** [comment]
```toml
[dependencies]
async-trait = "0.1.85"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138" }
thiserror = "2.0.11"
uniffi = { git = "http://github.com/mozilla/uniffi-rs", rev = "9c83e1de164b4168bd33bd991d22184ee9f6c856", optional = true }
```
